version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/baseapplication
permissions:
  - object: /home/ec2-user/baseapplication
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: code-deploy/applicationStop.sh
      timeout: 180
      runas: ec2-user
  BeforeInstall:
    - location: code-deploy/beforeInstall.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: code-deploy/afterInstall.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: code-deploy/applicationStart.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: code-deploy/validateService.sh
      timeout: 180
      runas: root

